# Generated by Django 5.2 on 2025-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_usuariosenhahash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuarioFuncao',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('CONSULTOR', 'Consultor'), ('COLABORADOR', 'Colaborador')], max_length=20, null=True),
        ),
    ]
