# Generated by Django 5.2 on 2025-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_usuariofuncao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuarioNome',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
